---
- name: Update apt cache
  changed_when: false
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: always

- ansible.builtin.import_tasks: fonts.yml
  tags: fonts
- ansible.builtin.import_tasks: kitty.yml
  tags: kitty
- ansible.builtin.import_tasks: fish.yml
  tags: fish
- ansible.builtin.import_tasks: starship.yml
  tags: starship
- ansible.builtin.import_tasks: i3wm.yml
  tags:
    - i3wm
    - ricing
- ansible.builtin.import_tasks: rofi.yml
  tags:
    - rofi
    - ricing
- ansible.builtin.import_tasks: picom.yml
  tags:
    - picom
    - ricing
